name: Build uturndata challenge solution

on:
  push:
    branches:
      - main  # Run workflow on push to the main branch
  workflow_dispatch: 
    
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Check out your repository

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6  # Replace with your required version

      - name: Terraform Validate
        run: |
            export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
            export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            export AWS_DEFAULT_REGION="us-east-2"
            cd ./01-infrastructure
            terraform init
            terraform validate
            echo "Validate completed successfully"
    
      - name: Terraform Plan
        run: |
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export AWS_DEFAULT_REGION="us-east-2"
          cd ./01-infrastructure
          terraform init
          terraform plan
          echo "Plan completed successfully"

      - name: Setup Packer
        uses: hashicorp/setup-packer@v2
        with:
            terraform_version: 1.9.2  # Replace with your required version

      - name: Packer Validate
        run: |
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export AWS_DEFAULT_REGION="us-east-2"
          cd ./02-packer
          packer init .
          packer validate ./flask_ami.pkr.hcl
          echo "Packer validate completed successfully"

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'  # Run only if triggered manually
        run: |
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          cd ./01-infrastructure
          pwd 
          env
          #terraform apply -auto-approve tfplan
