name: Build uturndata challenge solution

on:
  push:
    branches:
      - main  # Run workflow on push to the main branch
  workflow_dispatch: 
    
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Check out your repository

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6  # Replace with your required version

      - name: Terraform Validate
        run: |
            export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
            export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            export AWS_DEFAULT_REGION="${{ secrets.AWS_REGION }}"
            cd ./01-infrastructure
            terraform init
            terraform validate
            echo "NOTE: Terraform validate completed successfully."
    
      - name: Terraform Plan
        run: |
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export AWS_DEFAULT_REGION="${{ secrets.AWS_REGION }}"
          cd ./01-infrastructure
          terraform init
          terraform plan
          echo "NOTE: Terraform plan completed successfully."

      - name: Setup Packer
        uses: hashicorp/setup-packer@v2
        
      - name: Packer Validate
        run: |
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export AWS_DEFAULT_REGION="${{ secrets.AWS_REGION }}"
          cd ./02-packer
          packer init .
          packer validate ./flask_ami.pkr.hcl
          echo "NOTE: Packer validate completed successfully."

      - name: Build Infrastucture and AMI
        run: |
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export AWS_DEFAULT_REGION="${{ secrets.AWS_REGION }}"
          pwd
          ./apply.sh
          echo "NOTE: Build of Infrastructure and AMI completed successfully."

      - name: Validate Solution
        run: |
            export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
            export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            export AWS_DEFAULT_REGION="${{ secrets.AWS_REGION }}"
            dns_name=$(aws elbv2 describe-load-balancers --query "LoadBalancers[?LoadBalancerName=='challenge-alb'].DNSName" --output text)
            cd ./02-packer/scripts
            echo "NOTE: Running the provided test program."
            ./test_candidates.py $dns_name

          

